---
language: python
python: "3.6"
sudo: required
dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl

install:
  - sudo pip install ansible yamllint ansible-lint
  - echo -e 'localhost  ansible_connection=local' > tests/inventory
  - echo -e '[defaults]\nroles_path = ../\nhostfile = ./tests/inventory' > ansible.cfg

script:
  - echo "YAML lint"
  - yamllint -c tests/yamllint.yml .
  - echo "Ansible syntax check"
  - ansible-playbook --syntax-check tests/role.yml
  - ansible-playbook -v --diff tests/role.yml
  - ansible-playbook -v -D tests/role.yml
  - >
    ansible-playbook tests/role.yml --check
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

