---
- name: Docker | Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - curl
    state: present
    update_cache: yes

- name: Docker | Add the docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  notify: docker-apt-get-update

- name: Docker | Add the official docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: Docker | Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Docker | Create the /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    mode: 0700

- name: Docker | Add any additional docker startup options via the daemon.json config file
  copy:
    content: "{{ docker_additional_service_opts }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  notify: docker-restart-service

- name: Docker | Start the docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Docker | Add current user to docker group
  become: yes
  user:
    name: "{{ docker_user }}"
    groups: [docker]
    append: yes

# - name: Check that the docker.pid exists
#   stat:
#     path: /run/docker.pid
#   register: stat_result
#   failed_when: not stat_result.stat.exists
#   tags: docker_check

# - name: Result of check docker.pid
#   debug:
#     msg: Docker started
#   when: stat_result.stat.exists
#   tags: docker_check

- include_tasks: install-docker-compose.yml
  when: docker_install_compose | bool
  tags: docker_compose_only
